// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: stock.proto

package server

import (
	"context"

	"example/stock/i-kun.vip/pb/stock"
	"example/stock/internal/logic/stock"
	"example/stock/internal/svc"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) Ping(ctx context.Context, in *stock.Request) (*stock.Response, error) {
	l := stocklogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
