// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: order.proto

package order

import (
	"context"

	"example/order/i-kun.vip/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderCreateReq    = order.OrderCreateReq
	OrderCreateResp   = order.OrderCreateResp
	OrderRollbackReq  = order.OrderRollbackReq
	OrderRollbackResp = order.OrderRollbackResp
	Request           = order.Request
	Response          = order.Response

	Order interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
