// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: order.proto

package server

import (
	"context"

	"example/order/i-kun.vip/pb/order"
	"example/order/internal/logic/orderservice"
	"example/order/internal/svc"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServiceServer) OrderCreate(ctx context.Context, in *order.OrderCreateReq) (*order.OrderCreateResp, error) {
	l := orderservicelogic.NewOrderCreateLogic(ctx, s.svcCtx)
	return l.OrderCreate(in)
}

func (s *OrderServiceServer) OrderRevert(ctx context.Context, in *order.OrderRollbackReq) (*order.OrderRollbackResp, error) {
	l := orderservicelogic.NewOrderRevertLogic(ctx, s.svcCtx)
	return l.OrderRevert(in)
}
