// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: pay.proto

package orderpay

import (
	"context"

	"example/pay/i-kun.vip/pb/pay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderPayReq  = pay.OrderPayReq
	OrderPayResp = pay.OrderPayResp
	Request      = pay.Request
	Response     = pay.Response

	OrderPay interface {
		OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error)
	}

	defaultOrderPay struct {
		cli zrpc.Client
	}
)

func NewOrderPay(cli zrpc.Client) OrderPay {
	return &defaultOrderPay{
		cli: cli,
	}
}

func (m *defaultOrderPay) OrderPay(ctx context.Context, in *OrderPayReq, opts ...grpc.CallOption) (*OrderPayResp, error) {
	client := pay.NewOrderPayClient(m.cli.Conn())
	return client.OrderPay(ctx, in, opts...)
}
