// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: order.proto

package server

import (
	"context"

	"example/order/i-kun.vip/pb/order"
	"example/order/internal/logic/order"
	"example/order/internal/svc"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Ping(ctx context.Context, in *order.Request) (*order.Response, error) {
	l := orderlogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
