// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: stock.proto

package stock

import (
	"context"

	"example/stock/i-kun.vip/pb/stock"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = stock.Request
	Response = stock.Response

	Stock interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultStock struct {
		cli zrpc.Client
	}
)

func NewStock(cli zrpc.Client) Stock {
	return &defaultStock{
		cli: cli,
	}
}

func (m *defaultStock) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := stock.NewStockClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
