// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: pay.proto

package pay

import (
	"context"

	"example/pay/i-kun.vip/pb/pay"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderPayReq  = pay.OrderPayReq
	OrderPayResp = pay.OrderPayResp
	Request      = pay.Request
	Response     = pay.Response

	Pay interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPay struct {
		cli zrpc.Client
	}
)

func NewPay(cli zrpc.Client) Pay {
	return &defaultPay{
		cli: cli,
	}
}

func (m *defaultPay) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pay.NewPayClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
