// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: pay.proto

package server

import (
	"context"

	"example/pay/i-kun.vip/pb/pay"
	"example/pay/internal/logic/orderpay"
	"example/pay/internal/svc"
)

type OrderPayServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedOrderPayServer
}

func NewOrderPayServer(svcCtx *svc.ServiceContext) *OrderPayServer {
	return &OrderPayServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderPayServer) OrderPay(ctx context.Context, in *pay.OrderPayReq) (*pay.OrderPayResp, error) {
	l := orderpaylogic.NewOrderPayLogic(ctx, s.svcCtx)
	return l.OrderPay(in)
}
