// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: pay.proto

package pay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 创建支付记录
type OrderPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayName       string                 `protobuf:"bytes,3,opt,name=pay_name,json=payName,proto3" json:"pay_name,omitempty"`
	PayType       int64                  `protobuf:"varint,4,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayReq) Reset() {
	*x = OrderPayReq{}
	mi := &file_pay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayReq) ProtoMessage() {}

func (x *OrderPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayReq.ProtoReflect.Descriptor instead.
func (*OrderPayReq) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{2}
}

func (x *OrderPayReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPayReq) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderPayReq) GetPayName() string {
	if x != nil {
		return x.PayName
	}
	return ""
}

func (x *OrderPayReq) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

type OrderPayResp struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PayNo    string                 `protobuf:"bytes,1,opt,name=pay_no,json=payNo,proto3" json:"pay_no,omitempty"`
	PayUrl   string                 `protobuf:"bytes,2,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	PayId    string                 `protobuf:"bytes,3,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"`
	PayTime  string                 `protobuf:"bytes,4,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	PayPrice float32                `protobuf:"fixed32,5,opt,name=pay_price,json=payPrice,proto3" json:"pay_price,omitempty"`
	// 总价
	TotalPrice    float32 `protobuf:"fixed32,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPayResp) Reset() {
	*x = OrderPayResp{}
	mi := &file_pay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResp) ProtoMessage() {}

func (x *OrderPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResp.ProtoReflect.Descriptor instead.
func (*OrderPayResp) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPayResp) GetPayNo() string {
	if x != nil {
		return x.PayNo
	}
	return ""
}

func (x *OrderPayResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *OrderPayResp) GetPayId() string {
	if x != nil {
		return x.PayId
	}
	return ""
}

func (x *OrderPayResp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *OrderPayResp) GetPayPrice() float32 {
	if x != nil {
		return x.PayPrice
	}
	return 0
}

func (x *OrderPayResp) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_pay_proto protoreflect.FileDescriptor

const file_pay_proto_rawDesc = "" +
	"\n" +
	"\tpay.proto\x12\x03pay\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"y\n" +
	"\vOrderPayReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x19\n" +
	"\bpay_name\x18\x03 \x01(\tR\apayName\x12\x19\n" +
	"\bpay_type\x18\x04 \x01(\x03R\apayType\"\xae\x01\n" +
	"\fOrderPayResp\x12\x15\n" +
	"\x06pay_no\x18\x01 \x01(\tR\x05payNo\x12\x17\n" +
	"\apay_url\x18\x02 \x01(\tR\x06payUrl\x12\x15\n" +
	"\x06pay_id\x18\x03 \x01(\tR\x05payId\x12\x19\n" +
	"\bpay_time\x18\x04 \x01(\tR\apayTime\x12\x1b\n" +
	"\tpay_price\x18\x05 \x01(\x02R\bpayPrice\x12\x1f\n" +
	"\vtotal_price\x18\x06 \x01(\x02R\n" +
	"totalPrice2*\n" +
	"\x03Pay\x12#\n" +
	"\x04Ping\x12\f.pay.Request\x1a\r.pay.Response2;\n" +
	"\bOrderPay\x12/\n" +
	"\bOrderPay\x12\x10.pay.OrderPayReq\x1a\x11.pay.OrderPayRespB\x14Z\x12./i-kun.vip/pb/payb\x06proto3"

var (
	file_pay_proto_rawDescOnce sync.Once
	file_pay_proto_rawDescData []byte
)

func file_pay_proto_rawDescGZIP() []byte {
	file_pay_proto_rawDescOnce.Do(func() {
		file_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pay_proto_rawDesc), len(file_pay_proto_rawDesc)))
	})
	return file_pay_proto_rawDescData
}

var file_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pay_proto_goTypes = []any{
	(*Request)(nil),      // 0: pay.Request
	(*Response)(nil),     // 1: pay.Response
	(*OrderPayReq)(nil),  // 2: pay.OrderPayReq
	(*OrderPayResp)(nil), // 3: pay.OrderPayResp
}
var file_pay_proto_depIdxs = []int32{
	0, // 0: pay.Pay.Ping:input_type -> pay.Request
	2, // 1: pay.OrderPay.OrderPay:input_type -> pay.OrderPayReq
	1, // 2: pay.Pay.Ping:output_type -> pay.Response
	3, // 3: pay.OrderPay.OrderPay:output_type -> pay.OrderPayResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pay_proto_init() }
func file_pay_proto_init() {
	if File_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pay_proto_rawDesc), len(file_pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pay_proto_goTypes,
		DependencyIndexes: file_pay_proto_depIdxs,
		MessageInfos:      file_pay_proto_msgTypes,
	}.Build()
	File_pay_proto = out.File
	file_pay_proto_goTypes = nil
	file_pay_proto_depIdxs = nil
}
