// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type UserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

type UserInfoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoUpdateReq) Reset() {
	*x = UserInfoUpdateReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdateReq) ProtoMessage() {}

func (x *UserInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*UserInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

type UserInfoUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoUpdateResp) Reset() {
	*x = UserInfoUpdateResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdateResp) ProtoMessage() {}

func (x *UserInfoUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdateResp.ProtoReflect.Descriptor instead.
func (*UserInfoUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

type UserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

type UserRoleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleListReq) Reset() {
	*x = UserRoleListReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleListReq) ProtoMessage() {}

func (x *UserRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleListReq.ProtoReflect.Descriptor instead.
func (*UserRoleListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

type UserRoleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleListResp) Reset() {
	*x = UserRoleListResp{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleListResp) ProtoMessage() {}

func (x *UserRoleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleListResp.ProtoReflect.Descriptor instead.
func (*UserRoleListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

type UserRoleUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleUpdateReq) Reset() {
	*x = UserRoleUpdateReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleUpdateReq) ProtoMessage() {}

func (x *UserRoleUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleUpdateReq.ProtoReflect.Descriptor instead.
func (*UserRoleUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

type UserRoleUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleUpdateResp) Reset() {
	*x = UserRoleUpdateResp{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleUpdateResp) ProtoMessage() {}

func (x *UserRoleUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleUpdateResp.ProtoReflect.Descriptor instead.
func (*UserRoleUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

type UserRoleInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleInfoReq) Reset() {
	*x = UserRoleInfoReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleInfoReq) ProtoMessage() {}

func (x *UserRoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleInfoReq.ProtoReflect.Descriptor instead.
func (*UserRoleInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

type UserRoleInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleInfoResp) Reset() {
	*x = UserRoleInfoResp{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleInfoResp) ProtoMessage() {}

func (x *UserRoleInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleInfoResp.ProtoReflect.Descriptor instead.
func (*UserRoleInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

type UserRoleAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleAddReq) Reset() {
	*x = UserRoleAddReq{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleAddReq) ProtoMessage() {}

func (x *UserRoleAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleAddReq.ProtoReflect.Descriptor instead.
func (*UserRoleAddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

type UserRoleAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleAddResp) Reset() {
	*x = UserRoleAddResp{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleAddResp) ProtoMessage() {}

func (x *UserRoleAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleAddResp.ProtoReflect.Descriptor instead.
func (*UserRoleAddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

type UserRoleDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleDeleteReq) Reset() {
	*x = UserRoleDeleteReq{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleDeleteReq) ProtoMessage() {}

func (x *UserRoleDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleDeleteReq.ProtoReflect.Descriptor instead.
func (*UserRoleDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

type UserRoleDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleDeleteResp) Reset() {
	*x = UserRoleDeleteResp{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleDeleteResp) ProtoMessage() {}

func (x *UserRoleDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleDeleteResp.ProtoReflect.Descriptor instead.
func (*UserRoleDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

type UserClassListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassListReq) Reset() {
	*x = UserClassListReq{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassListReq) ProtoMessage() {}

func (x *UserClassListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassListReq.ProtoReflect.Descriptor instead.
func (*UserClassListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

type UserClassListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassListResp) Reset() {
	*x = UserClassListResp{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassListResp) ProtoMessage() {}

func (x *UserClassListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassListResp.ProtoReflect.Descriptor instead.
func (*UserClassListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

type UserClassUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassUpdateReq) Reset() {
	*x = UserClassUpdateReq{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassUpdateReq) ProtoMessage() {}

func (x *UserClassUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassUpdateReq.ProtoReflect.Descriptor instead.
func (*UserClassUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

type UserClassUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassUpdateResp) Reset() {
	*x = UserClassUpdateResp{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassUpdateResp) ProtoMessage() {}

func (x *UserClassUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassUpdateResp.ProtoReflect.Descriptor instead.
func (*UserClassUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

type UserClassInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassInfoReq) Reset() {
	*x = UserClassInfoReq{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassInfoReq) ProtoMessage() {}

func (x *UserClassInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassInfoReq.ProtoReflect.Descriptor instead.
func (*UserClassInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

type UserClassInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassInfoResp) Reset() {
	*x = UserClassInfoResp{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassInfoResp) ProtoMessage() {}

func (x *UserClassInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassInfoResp.ProtoReflect.Descriptor instead.
func (*UserClassInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

type UserClassAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassAddReq) Reset() {
	*x = UserClassAddReq{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassAddReq) ProtoMessage() {}

func (x *UserClassAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassAddReq.ProtoReflect.Descriptor instead.
func (*UserClassAddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

type UserClassAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassAddResp) Reset() {
	*x = UserClassAddResp{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassAddResp) ProtoMessage() {}

func (x *UserClassAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassAddResp.ProtoReflect.Descriptor instead.
func (*UserClassAddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

type UserClassDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassDeleteReq) Reset() {
	*x = UserClassDeleteReq{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassDeleteReq) ProtoMessage() {}

func (x *UserClassDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassDeleteReq.ProtoReflect.Descriptor instead.
func (*UserClassDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

type UserClassDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserClassDeleteResp) Reset() {
	*x = UserClassDeleteResp{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserClassDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserClassDeleteResp) ProtoMessage() {}

func (x *UserClassDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserClassDeleteResp.ProtoReflect.Descriptor instead.
func (*UserClassDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\n" +
	"\n" +
	"\bLoginReq\"\v\n" +
	"\tLoginResp\"\r\n" +
	"\vUserInfoReq\"\x0e\n" +
	"\fUserInfoResp\"\x13\n" +
	"\x11UserInfoUpdateReq\"\x14\n" +
	"\x12UserInfoUpdateResp\"\r\n" +
	"\vUserListReq\"\x0e\n" +
	"\fUserListResp\"\x11\n" +
	"\x0fUserRoleListReq\"\x12\n" +
	"\x10UserRoleListResp\"\x13\n" +
	"\x11UserRoleUpdateReq\"\x14\n" +
	"\x12UserRoleUpdateResp\"\x11\n" +
	"\x0fUserRoleInfoReq\"\x12\n" +
	"\x10UserRoleInfoResp\"\x10\n" +
	"\x0eUserRoleAddReq\"\x11\n" +
	"\x0fUserRoleAddResp\"\x13\n" +
	"\x11UserRoleDeleteReq\"\x14\n" +
	"\x12UserRoleDeleteResp\"\x12\n" +
	"\x10UserClassListReq\"\x13\n" +
	"\x11UserClassListResp\"\x14\n" +
	"\x12UserClassUpdateReq\"\x15\n" +
	"\x13UserClassUpdateResp\"\x12\n" +
	"\x10UserClassInfoReq\"\x13\n" +
	"\x11UserClassInfoResp\"\x11\n" +
	"\x0fUserClassAddReq\"\x12\n" +
	"\x10UserClassAddResp\"\x14\n" +
	"\x12UserClassDeleteReq\"\x15\n" +
	"\x13UserClassDeleteResp2\xe2\x01\n" +
	"\vUserService\x12(\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x121\n" +
	"\bUserInfo\x12\x11.user.UserInfoReq\x1a\x12.user.UserInfoResp\x12C\n" +
	"\x0eUserInfoUpdate\x12\x17.user.UserInfoUpdateReq\x1a\x18.user.UserInfoUpdateResp\x121\n" +
	"\bUserList\x12\x11.user.UserListReq\x1a\x12.user.UserListResp2\xd5\x02\n" +
	"\x0fUserRoleService\x12=\n" +
	"\fUserRoleList\x12\x15.user.UserRoleListReq\x1a\x16.user.UserRoleListResp\x12C\n" +
	"\x0eUserRoleUpdate\x12\x17.user.UserRoleUpdateReq\x1a\x18.user.UserRoleUpdateResp\x12=\n" +
	"\fUserRoleInfo\x12\x15.user.UserRoleInfoReq\x1a\x16.user.UserRoleInfoResp\x12:\n" +
	"\vUserRoleAdd\x12\x14.user.UserRoleAddReq\x1a\x15.user.UserRoleAddResp\x12C\n" +
	"\x0eUserRoleDelete\x12\x17.user.UserRoleDeleteReq\x1a\x18.user.UserRoleDeleteResp2\xe5\x02\n" +
	"\x10UserClassService\x12@\n" +
	"\rUserClassList\x12\x16.user.UserClassListReq\x1a\x17.user.UserClassListResp\x12F\n" +
	"\x0fUserClassUpdate\x12\x18.user.UserClassUpdateReq\x1a\x19.user.UserClassUpdateResp\x12@\n" +
	"\rUserClassInfo\x12\x16.user.UserClassInfoReq\x1a\x17.user.UserClassInfoResp\x12=\n" +
	"\fUserClassAdd\x12\x15.user.UserClassAddReq\x1a\x16.user.UserClassAddResp\x12F\n" +
	"\x0fUserClassDelete\x12\x18.user.UserClassDeleteReq\x1a\x19.user.UserClassDeleteRespB\x13Z\x11i-kun.vip/pb/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_user_proto_goTypes = []any{
	(*LoginReq)(nil),            // 0: user.LoginReq
	(*LoginResp)(nil),           // 1: user.LoginResp
	(*UserInfoReq)(nil),         // 2: user.UserInfoReq
	(*UserInfoResp)(nil),        // 3: user.UserInfoResp
	(*UserInfoUpdateReq)(nil),   // 4: user.UserInfoUpdateReq
	(*UserInfoUpdateResp)(nil),  // 5: user.UserInfoUpdateResp
	(*UserListReq)(nil),         // 6: user.UserListReq
	(*UserListResp)(nil),        // 7: user.UserListResp
	(*UserRoleListReq)(nil),     // 8: user.UserRoleListReq
	(*UserRoleListResp)(nil),    // 9: user.UserRoleListResp
	(*UserRoleUpdateReq)(nil),   // 10: user.UserRoleUpdateReq
	(*UserRoleUpdateResp)(nil),  // 11: user.UserRoleUpdateResp
	(*UserRoleInfoReq)(nil),     // 12: user.UserRoleInfoReq
	(*UserRoleInfoResp)(nil),    // 13: user.UserRoleInfoResp
	(*UserRoleAddReq)(nil),      // 14: user.UserRoleAddReq
	(*UserRoleAddResp)(nil),     // 15: user.UserRoleAddResp
	(*UserRoleDeleteReq)(nil),   // 16: user.UserRoleDeleteReq
	(*UserRoleDeleteResp)(nil),  // 17: user.UserRoleDeleteResp
	(*UserClassListReq)(nil),    // 18: user.UserClassListReq
	(*UserClassListResp)(nil),   // 19: user.UserClassListResp
	(*UserClassUpdateReq)(nil),  // 20: user.UserClassUpdateReq
	(*UserClassUpdateResp)(nil), // 21: user.UserClassUpdateResp
	(*UserClassInfoReq)(nil),    // 22: user.UserClassInfoReq
	(*UserClassInfoResp)(nil),   // 23: user.UserClassInfoResp
	(*UserClassAddReq)(nil),     // 24: user.UserClassAddReq
	(*UserClassAddResp)(nil),    // 25: user.UserClassAddResp
	(*UserClassDeleteReq)(nil),  // 26: user.UserClassDeleteReq
	(*UserClassDeleteResp)(nil), // 27: user.UserClassDeleteResp
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.UserService.Login:input_type -> user.LoginReq
	2,  // 1: user.UserService.UserInfo:input_type -> user.UserInfoReq
	4,  // 2: user.UserService.UserInfoUpdate:input_type -> user.UserInfoUpdateReq
	6,  // 3: user.UserService.UserList:input_type -> user.UserListReq
	8,  // 4: user.UserRoleService.UserRoleList:input_type -> user.UserRoleListReq
	10, // 5: user.UserRoleService.UserRoleUpdate:input_type -> user.UserRoleUpdateReq
	12, // 6: user.UserRoleService.UserRoleInfo:input_type -> user.UserRoleInfoReq
	14, // 7: user.UserRoleService.UserRoleAdd:input_type -> user.UserRoleAddReq
	16, // 8: user.UserRoleService.UserRoleDelete:input_type -> user.UserRoleDeleteReq
	18, // 9: user.UserClassService.UserClassList:input_type -> user.UserClassListReq
	20, // 10: user.UserClassService.UserClassUpdate:input_type -> user.UserClassUpdateReq
	22, // 11: user.UserClassService.UserClassInfo:input_type -> user.UserClassInfoReq
	24, // 12: user.UserClassService.UserClassAdd:input_type -> user.UserClassAddReq
	26, // 13: user.UserClassService.UserClassDelete:input_type -> user.UserClassDeleteReq
	1,  // 14: user.UserService.Login:output_type -> user.LoginResp
	3,  // 15: user.UserService.UserInfo:output_type -> user.UserInfoResp
	5,  // 16: user.UserService.UserInfoUpdate:output_type -> user.UserInfoUpdateResp
	7,  // 17: user.UserService.UserList:output_type -> user.UserListResp
	9,  // 18: user.UserRoleService.UserRoleList:output_type -> user.UserRoleListResp
	11, // 19: user.UserRoleService.UserRoleUpdate:output_type -> user.UserRoleUpdateResp
	13, // 20: user.UserRoleService.UserRoleInfo:output_type -> user.UserRoleInfoResp
	15, // 21: user.UserRoleService.UserRoleAdd:output_type -> user.UserRoleAddResp
	17, // 22: user.UserRoleService.UserRoleDelete:output_type -> user.UserRoleDeleteResp
	19, // 23: user.UserClassService.UserClassList:output_type -> user.UserClassListResp
	21, // 24: user.UserClassService.UserClassUpdate:output_type -> user.UserClassUpdateResp
	23, // 25: user.UserClassService.UserClassInfo:output_type -> user.UserClassInfoResp
	25, // 26: user.UserClassService.UserClassAdd:output_type -> user.UserClassAddResp
	27, // 27: user.UserClassService.UserClassDelete:output_type -> user.UserClassDeleteResp
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
