// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: order.proto

package orderservice

import (
	"context"

	"example/order/i-kun.vip/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderCreateReq    = order.OrderCreateReq
	OrderCreateResp   = order.OrderCreateResp
	OrderRollbackReq  = order.OrderRollbackReq
	OrderRollbackResp = order.OrderRollbackResp
	Request           = order.Request
	Response          = order.Response

	OrderService interface {
		OrderCreate(ctx context.Context, in *OrderCreateReq, opts ...grpc.CallOption) (*OrderCreateResp, error)
		OrderRevert(ctx context.Context, in *OrderRollbackReq, opts ...grpc.CallOption) (*OrderRollbackResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

func (m *defaultOrderService) OrderCreate(ctx context.Context, in *OrderCreateReq, opts ...grpc.CallOption) (*OrderCreateResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.OrderCreate(ctx, in, opts...)
}

func (m *defaultOrderService) OrderRevert(ctx context.Context, in *OrderRollbackReq, opts ...grpc.CallOption) (*OrderRollbackResp, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.OrderRevert(ctx, in, opts...)
}
