// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: pay.proto

package server

import (
	"context"

	"example/pay/i-kun.vip/pb/pay"
	"example/pay/internal/logic/pay"
	"example/pay/internal/svc"
)

type PayServer struct {
	svcCtx *svc.ServiceContext
	pay.UnimplementedPayServer
}

func NewPayServer(svcCtx *svc.ServiceContext) *PayServer {
	return &PayServer{
		svcCtx: svcCtx,
	}
}

func (s *PayServer) Ping(ctx context.Context, in *pay.Request) (*pay.Response, error) {
	l := paylogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
